# Generated by Django 4.2.1 on 2023-05-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=15)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creadet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Creadet', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('borrow', 'Взять в долг'), ('repay', 'Погасить займ'), ('lend', 'Дать в долг'), ('receive', 'Принять погашение')], default='borrow', max_length=20, verbose_name='Transaction type')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.contact')),
            ],
        ),
    ]
