# Generated by Django 4.2.1 on 2023-05-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='creadet',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Creadet',
            new_name='created',
        ),
    ]
