# Generated by Django 4.2.1 on 2023-07-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_transaction_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loans.transaction')),
                ('repayment_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
