# Generated by Django 4.2.1 on 2023-07-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_notification_transaction_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('message_text', models.TextField()),
                ('message_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact_photos/'),
        ),
    ]
