# Generated by Django 4.2.1 on 2023-07-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_contact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='photo',
        ),
    ]
